DROP TABLE IF EXISTS CUSTOMERS;
DROP TABLE IF EXISTS SELLERS;
DROP TABLE IF EXISTS SALES;
DROP TABLE IF EXISTS SALE_ITEMS;

CREATE TABLE CUSTOMERS (
   job_id BIGINT NOT NULL,
   document VARCHAR(255) NULL,
   name VARCHAR(255) NOT NULL,
   business_area VARCHAR(255) NULL
);

CREATE TABLE SELLERS (
   job_id BIGINT NOT NULL,
   document VARCHAR(255) NULL,
   name VARCHAR(255) NOT NULL,
   salary REAL NULL
);

CREATE TABLE SALES (
   job_id BIGINT NOT NULL,
   id BIGINT NOT NULL,
   seller VARCHAR(255) NOT NULL
);

CREATE TABLE SALE_ITEMS (
   job_id BIGINT NOT NULL,
   sale_id BIGINT NOT NULL,
   id BIGINT NOT NULL,
   quantity INT NOT NULL,
   price REAL NULL
);

CREATE INDEX CUSTOMERS_IDX
ON CUSTOMERS(job_id);

CREATE INDEX SELLERS_IDX
ON SELLERS(job_id);

CREATE INDEX SALES_IDX
ON SALES(id, job_id);

CREATE INDEX SALE_ITEMS_IDX
ON SALE_ITEMS(sale_id, job_id);